parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Common/Kernel.php'

    # Exception's throwing event listener
    App\Common\EventListener\ExceptionListener:
        arguments:
            $env: '%environment%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }


    App\Tests\Tools\DataFixture\:
        resource: '../tests/Tools/DataFixture/'

