version: "3.8"

services:
  php-fpm:
    container_name: testing-sys-php-fpm
    build:
      context: ./../../
      dockerfile: ./.deployment/docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Testing-sys"
    volumes:
      - ./../../:/var/www/

  nginx:
    container_name: testing-sys-nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ../../:/var/www:rw
    depends_on:
      - php-fpm

  postgres:
    container_name: testing-sys-db
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
